version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react_vite_app
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    networks:
      - app-network

  celery:
    build: ./backend
    container_name: celery_worker
    command: celery -A app worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - app-network
      -
networks:
  app-network:
    driver: bridge
