version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - ./.env
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: django_app
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    container_name: react_vite_app
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

  celery:
    build: ./backend
    container_name: celery_worker
    command: celery -A app worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: